export const APP_STATUS = {
  INSTALLED: "installed",
  UNINSTALLED: "uninstalled",
};

export const WEBHOOK_TOPICS = {
  APP_UNINSTALLED: "APP_UNINSTALLED",
  SHOP_UPDATE: "SHOP_UPDATE",
  CHECKOUTS_UPDATE: "CHECKOUTS_UPDATE",
  CHECKOUTS_DELETE: "CHECKOUTS_DELETE",
};

export const WEBHOOK_PATH = "/webhooks";
